### ISSUE TITLE
[API] As API user, I would like to be able to calculate offers for Salesroute of type "MPD - Sante / Prevoyance" 

### ISSUE THREAD

**Issue by DominiqueBertrand** [DominiqueBertrand/coog-fed-planning#33]
### TODOs
 * [ ] Configure coog BO to allow the calculation of the offers
 * [ ] Modify current MGEFI functional tests to allow testing of the functionality above.
 * [ ] Update current MGEFI mock server data.

### Resources:
* Testing URL: ?
* Staging URL: ?
