### ISSUE TITLE
[API] - Add new entry "groups" into "questionnaire / part" to allow question group management.

### ISSUE THREAD

**Issue by DominiqueBertrand** [DominiqueBertrand/coog-fed-planning#43]
### TODO:
 * [ ] add the new entry into Coog Gateway
 * [ ] add Swagger documentation related to the new entry
 * [ ] add functional tests related to the new entry 

### Dependencies
=> Blocked by [13077](https://support.coopengo.com/issues/13077)

#### Questionnaire:
```
{
   "id":Integer,
   "title":String,
   "mandatory":boolean,
   "sequence":Integer,
   "description":String,
   "questions":[
      Question
   ],
   "groups":[
      Group
   ]
}
```
#### Group:
```
{
   "questions":[
                     {
                             "code":String,
                             "sequence":Integer                  
      }           
   ],
           "title":String,
           "description":String,
           "tooltip":String
}
```

### Exemple de groups: 
```
"groups":[
      {
         "questions":[
            {
               "code":"refund_question",
               "sequence":"1"
            }
         ],
         "title":"Couverture globale",
         "description":""
      },
      {
         "questions":[
            {
               "code":"question_1",
               "sequence":"1"
            },
            {
               "code":"question_2",
               "sequence":"2"
            },
            {
               "code":"question_3",
               "sequence":"3"
            }
         ],
         "title":"Optique",
         "description":"Vos besoins en matiere d'optique"
      }
   ]
```

**Comment by PierreCookie** [comment]
Travail effectué dans coog
