### ISSUE TITLE
[B2B] EditSalesRoute / QuotationBlock : Update fields for Protectio DC

### ISSUE THREAD

**Issue by DominiqueBertrand** [DominiqueBertrand/coog-fed-planning#93]
### Description
The following fields should be displayed in the QuotationBlock ("Les Informations")
- Civilité
- Nom de famille
- Prénom
- Date de naissance
- E-mail du devis
- Téléphone du devis
- Adresse
- Complément d'adresse
- Code postal
- Ville
- Numéro de sécurité sociale
- Date d'adhésion MGEFI
- Date d'effet au contrat

### Todo
- [ ]  Add the following fields: 
   - [ ]  Numéro de sécurité sociale
   - [ ]  Date d'adhésion MGEFI 
 - Delete the field 
   - [ ] Nombre d'enfants à charge"
